=== acmiyaguchi/mozilla-pipeline-schemas/schemas/eng-workflow/bmobugs/bmobugs.1.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "properties": {
    "assigned_to": {
      "type": "integer"
    },
    "blocked_by": {
      "items": {
        "type": "integer"
      },
      "type": "array"
    },
    "bug_id": {
      "minimum": 1,
      "type": "integer"
    },
    "bug_severity": {
      "type": "string"
    },
    "bug_status": {
      "type": "string"
    },
    "component": {
      "type": "string"
    },
    "creation_ts": {
      "type": "string"
    },
    "delta_ts": {
      "type": "string"
    },
    "depends_on": {
      "items": {
        "type": "integer"
      },
      "type": "array"
    },
    "duplicate_of": {
      "type": [
        "null",
        "integer"
      ]
    },
    "duplicates": {
      "items": {
        "type": "integer"
      },
      "type": "array"
    },
    "flags": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "name": {
            "type": "string"
          },
          "requestee_id": {
            "type": [
              "null",
              "integer"
            ]
          },
          "setter_id": {
            "type": "integer"
          },
          "status": {
            "enum": [
              "?",
              "+",
              "-"
            ],
            "type": "string"
          }
        },
        "required": [
          "status",
          "name",
          "setter_id",
          "requestee_id"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "groups": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "keywords": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "priority": {
      "type": "string"
    },
    "product": {
      "type": "string"
    },
    "qa_contact": {
      "type": [
        "null",
        "integer"
      ]
    },
    "reporter": {
      "type": "integer"
    },
    "resolution": {
      "type": "string"
    },
    "target_milestone": {
      "type": "string"
    },
    "version": {
      "type": "string"
    }
  },
  "required": [
    "priority",
    "blocked_by",
    "duplicate_of",
    "bug_id",
    "reporter",
    "keywords",
    "duplicates",
    "assigned_to",
    "creation_ts",
    "groups",
    "qa_contact",
    "bug_severity",
    "depends_on",
    "bug_status",
    "delta_ts",
    "flags",
    "version",
    "component",
    "product",
    "target_milestone"
  ],
  "type": "object"
}

=== acmiyaguchi/mozilla-pipeline-schemas/validation/eng-workflow/bmobugs.1.flags.pass.json
{
   "assigned_to" : 1,
   "blocked_by" : [],
   "bug_id" : 1526431,
   "bug_severity" : "normal",
   "bug_status" : "NEW",
   "component" : "Testing",
   "creation_ts" : "2019-02-08 11:09:58",
   "delta_ts" : "2019-02-08T12:14:22",
   "depends_on" : [],
   "duplicate_of" : null,
   "duplicates" : [],
   "flags" : [
      {
         "name" : "needinfo",
         "requestee_id" : 408096,
         "setter_id" : 23402,
         "status" : "?"
      }
   ],
   "groups" : [],
   "keywords" : [],
   "priority" : "--",
   "product" : "Firefox for Android",
   "qa_contact" : null,
   "reporter" : 474533,
   "resolution" : "",
   "target_milestone" : "---",
   "version" : "unspecified"
}

=== acmiyaguchi/mozilla-pipeline-schemas/validation/eng-workflow/bmobugs.1.oldone.pass.json
{
   "assigned_to" : 99,
   "blocked_by" : [],
   "bug_id" : 200,
   "bug_severity" : "trivial",
   "bug_status" : "VERIFIED",
   "component" : "Layout",
   "creation_ts" : "1998-04-14 02:09:13",
   "delta_ts" : "2008-11-21T13:41:32",
   "depends_on" : [],
   "duplicate_of" : null,
   "duplicates" : [],
   "flags" : [],
   "groups" : [],
   "keywords" : [],
   "priority" : "P3",
   "product" : "MozillaClassic Graveyard",
   "qa_contact" : null,
   "reporter" : 86,
   "resolution" : "FIXED",
   "target_milestone" : "---",
   "version" : "1998-03-31"
}

=== acmiyaguchi/mozilla-pipeline-schemas/validation/eng-workflow/bmobugs.1.newer.pass.json
{
   "assigned_to" : 1,
   "blocked_by" : [
      1526109
   ],
   "bug_id" : 1526430,
   "bug_severity" : "normal",
   "bug_status" : "NEW",
   "component" : "Application Update",
   "creation_ts" : "2019-02-08 11:09:26",
   "delta_ts" : "2019-02-08T11:21:12",
   "depends_on" : [
      1524400
   ],
   "duplicate_of" : null,
   "duplicates" : [],
   "flags" : [],
   "groups" : [],
   "keywords" : [
      "regression",
      "intermittent-failure"
   ],
   "priority" : "P5",
   "product" : "Toolkit",
   "qa_contact" : null,
   "reporter" : 573381,
   "resolution" : "",
   "target_milestone" : "---",
   "version" : "unspecified"
}
