=== acmiyaguchi/mozilla-pipeline-schemas/templates/webpagetest/webpagetest-run/webpagetest-run.1.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "webpagetest-run",
  "description": "Web-performance metrics",
  "properties": {
    "appName": {
      "type": "string"
    },
    "channel": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "connection": {
      "type": "string"
    },
    "url": {
      "type": "string"
    },
    "platform": {
      "type": "string",
      "enum": ["desktop", "mobile"]
    },
    "runner": {
      "type": "string"
    },
    "runId": {
      "type": "string"
    },
    "sessionState": {
      "type": "string",
      "enum": ["auth", "noAuth"]
    },
    "metrics": {
      "additionalProperties": {
        "properties": {
          "firstView": {
            "properties": {
              "median": {
                "type": "number"
              },
              "standardDeviation": {
                "type": "number"
              }
            },
            "anyOf": [
              {"required": ["median"]},
              {"required": ["standardDeviation"]}
            ],
            "type": "object"
          }
        },
        "required": ["firstView"],
        "type": "object"
      },
      "type": "object"
    }
  },
  "required": ["appName", "channel", "version", "connection", "url", "platform", "runner", "runId", "sessionState", "metrics"],
  "additionalProperties": false
}

=== acmiyaguchi/mozilla-pipeline-schemas/validation/webpagetest/webpagetest-run.1.median_only.pass.json
{
  "appName": "firefox",
  "channel": "release",
  "version": "63.0",
  "connection": "cable",
  "url": "wikipedia.org",
  "platform": "desktop",
  "metrics": {
    "firstPaint": {
      "firstView": {
        "median": 4.2
      }
    },
    "render": {
      "firstView": {
        "median": 11
      }
    },
    "visualComplete": {
      "firstView": {
        "median": 10
      }
    },
    "SpeedIndex": {
      "firstView": {
        "median": 20
      }
    }
  },
  "runner": "jenkins-prod",
  "runId": "jenkins-wpt/google-123",
  "sessionState": "noAuth"
}

=== acmiyaguchi/mozilla-pipeline-schemas/validation/webpagetest/webpagetest-run.1.sample.pass.json
{
  "appName": "firefox",
  "channel": "release",
  "version": "63.0",
  "connection": "cable",
  "url": "wikipedia.org",
  "platform": "desktop",
  "metrics": {
    "firstPaint": {
      "firstView": {
        "median": 4.2,
        "standardDeviation": 2
      }
    },
    "render": {
      "firstView": {
        "median": 11,
        "standardDeviation": 2
      }
    },
    "visualComplete": {
      "firstView": {
        "median": 10,
        "standardDeviation": 2
      }
    },
    "SpeedIndex": {
      "firstView": {
        "median": 20,
        "standardDeviation": 2
      }
    }
  },
  "runner": "jenkins-prod",
  "runId": "jenkins-wpt/google-123",
  "sessionState": "noAuth"
}
